def exception(e):
    print(f'\nEXCEPTION: {e}\n')